package com.qf.pojo;

public class TbCollection {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collection.collid
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private Integer collid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collection.user_id
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_collection.goods_id
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private Integer goodsId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collection.collid
     *
     * @return the value of tb_collection.collid
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public Integer getCollid() {
        return collid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collection.collid
     *
     * @param collid the value for tb_collection.collid
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setCollid(Integer collid) {
        this.collid = collid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collection.user_id
     *
     * @return the value of tb_collection.user_id
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collection.user_id
     *
     * @param userId the value for tb_collection.user_id
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_collection.goods_id
     *
     * @return the value of tb_collection.goods_id
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_collection.goods_id
     *
     * @param goodsId the value for tb_collection.goods_id
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }
}