package com.qf.pojo;

public class TbImg {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_img.imgid
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    private Integer imgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_img.goods_id
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_img.img_url
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    private String imgUrl;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_img.imgid
     *
     * @return the value of tb_img.imgid
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    public Integer getImgid() {
        return imgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_img.imgid
     *
     * @param imgid the value for tb_img.imgid
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    public void setImgid(Integer imgid) {
        this.imgid = imgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_img.goods_id
     *
     * @return the value of tb_img.goods_id
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_img.goods_id
     *
     * @param goodsId the value for tb_img.goods_id
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_img.img_url
     *
     * @return the value of tb_img.img_url
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    public String getImgUrl() {
        return imgUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_img.img_url
     *
     * @param imgUrl the value for tb_img.img_url
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    public void setImgUrl(String imgUrl) {
        this.imgUrl = imgUrl == null ? null : imgUrl.trim();
    }
}