package com.qf.pojo;

public class TbOrderDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_detail.odid
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    private Integer odid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_detail.goods_id
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    private Integer goodsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_detail.order_id
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    private Integer orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order_detail.goods_num
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    private Integer goodsNum;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_detail.odid
     *
     * @return the value of tb_order_detail.odid
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    public Integer getOdid() {
        return odid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_detail.odid
     *
     * @param odid the value for tb_order_detail.odid
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    public void setOdid(Integer odid) {
        this.odid = odid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_detail.goods_id
     *
     * @return the value of tb_order_detail.goods_id
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    public Integer getGoodsId() {
        return goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_detail.goods_id
     *
     * @param goodsId the value for tb_order_detail.goods_id
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    public void setGoodsId(Integer goodsId) {
        this.goodsId = goodsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_detail.order_id
     *
     * @return the value of tb_order_detail.order_id
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    public Integer getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_detail.order_id
     *
     * @param orderId the value for tb_order_detail.order_id
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    public void setOrderId(Integer orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order_detail.goods_num
     *
     * @return the value of tb_order_detail.goods_num
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    public Integer getGoodsNum() {
        return goodsNum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order_detail.goods_num
     *
     * @param goodsNum the value for tb_order_detail.goods_num
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    public void setGoodsNum(Integer goodsNum) {
        this.goodsNum = goodsNum;
    }
}