package com.qf.pojo;

import java.util.Date;

public class TbOrder {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.orderid
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private String orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.order_status
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private Integer orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.user_id
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private Integer userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.count
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private Integer count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.total_price
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private Double totalPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.pay
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private String pay;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.notes
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private String notes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_order.pay_time
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private Date payTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.orderid
     *
     * @return the value of tb_order.orderid
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public String getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.orderid
     *
     * @param orderid the value for tb_order.orderid
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setOrderid(String orderid) {
        this.orderid = orderid == null ? null : orderid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.order_status
     *
     * @return the value of tb_order.order_status
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public Integer getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.order_status
     *
     * @param orderStatus the value for tb_order.order_status
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setOrderStatus(Integer orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.user_id
     *
     * @return the value of tb_order.user_id
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.user_id
     *
     * @param userId the value for tb_order.user_id
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.count
     *
     * @return the value of tb_order.count
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public Integer getCount() {
        return count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.count
     *
     * @param count the value for tb_order.count
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setCount(Integer count) {
        this.count = count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.total_price
     *
     * @return the value of tb_order.total_price
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public Double getTotalPrice() {
        return totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.total_price
     *
     * @param totalPrice the value for tb_order.total_price
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setTotalPrice(Double totalPrice) {
        this.totalPrice = totalPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.pay
     *
     * @return the value of tb_order.pay
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public String getPay() {
        return pay;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.pay
     *
     * @param pay the value for tb_order.pay
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setPay(String pay) {
        this.pay = pay == null ? null : pay.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.notes
     *
     * @return the value of tb_order.notes
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public String getNotes() {
        return notes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.notes
     *
     * @param notes the value for tb_order.notes
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setNotes(String notes) {
        this.notes = notes == null ? null : notes.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_order.pay_time
     *
     * @return the value of tb_order.pay_time
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_order.pay_time
     *
     * @param payTime the value for tb_order.pay_time
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }
}