package com.qf.pojo;

public class TbUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.uid
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private Integer uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.phone
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.nickname
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private String nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.password
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.avatar
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_user.flag
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    private Integer flag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.uid
     *
     * @return the value of tb_user.uid
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.uid
     *
     * @param uid the value for tb_user.uid
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.phone
     *
     * @return the value of tb_user.phone
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.phone
     *
     * @param phone the value for tb_user.phone
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.nickname
     *
     * @return the value of tb_user.nickname
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.nickname
     *
     * @param nickname the value for tb_user.nickname
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.password
     *
     * @return the value of tb_user.password
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.password
     *
     * @param password the value for tb_user.password
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.avatar
     *
     * @return the value of tb_user.avatar
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.avatar
     *
     * @param avatar the value for tb_user.avatar
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar == null ? null : avatar.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_user.flag
     *
     * @return the value of tb_user.flag
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public Integer getFlag() {
        return flag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_user.flag
     *
     * @param flag the value for tb_user.flag
     *
     * @mbg.generated Sat Jul 18 16:00:17 CST 2020
     */
    public void setFlag(Integer flag) {
        this.flag = flag;
    }
}