package com.qf.mapper;

import com.qf.pojo.TbHistory;
import com.qf.pojo.TbHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TbHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    long countByExample(TbHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    int deleteByExample(TbHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    int deleteByPrimaryKey(Integer histroyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    int insert(TbHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    int insertSelective(TbHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    List<TbHistory> selectByExample(TbHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    TbHistory selectByPrimaryKey(Integer histroyid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    int updateByExampleSelective(@Param("record") TbHistory record, @Param("example") TbHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    int updateByExample(@Param("record") TbHistory record, @Param("example") TbHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    int updateByPrimaryKeySelective(TbHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_history
     *
     * @mbg.generated Tue Jul 14 22:53:58 CST 2020
     */
    int updateByPrimaryKey(TbHistory record);
}